import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { listAuditLogs } from "@/modules/audit/query";

export default async function AuditPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams;
  const rows = await listAuditLogs({
    action: filters.action?.trim() || undefined,
    actorType: ["ADMIN", "CUSTOMER", "SYSTEM"].includes(filters.actorType ?? "") ? filters.actorType as "ADMIN" | "CUSTOMER" | "SYSTEM" : undefined,
    entityType: filters.entityType?.trim() || undefined,
  });
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold tracking-tight text-ink sm:text-3xl">审计日志</h1><p className="mt-2 text-sm text-muted">只读查看客户、商品、价格和库存的重要变更记录。</p></header><form className="grid gap-3 rounded-[var(--radius-surface)] border border-border bg-background p-4 sm:grid-cols-3" method="get"><label className="space-y-2 text-sm font-medium">操作类型<input className="min-h-11 w-full rounded-lg border border-border px-3" name="action" placeholder="例如 INVENTORY_ADJUSTED" /></label><label className="space-y-2 text-sm font-medium">主体类型<select className="min-h-11 w-full rounded-lg border border-border bg-background px-3" name="actorType"><option value="">全部</option><option value="ADMIN">管理员</option><option value="CUSTOMER">客户</option><option value="SYSTEM">系统</option></select></label><label className="space-y-2 text-sm font-medium">对象类型<input className="min-h-11 w-full rounded-lg border border-border px-3" name="entityType" placeholder="例如 SKU_INVENTORY" /></label><button className="min-h-11 rounded-lg bg-primary px-4 text-sm font-semibold text-white sm:col-span-3 sm:w-fit" type="submit">筛选日志</button></form><section className="overflow-hidden rounded-[var(--radius-surface)] border border-border bg-background"><Table><TableHeader><TableRow><TableHead>时间</TableHead><TableHead>操作主体</TableHead><TableHead>操作</TableHead><TableHead>对象</TableHead><TableHead>原因</TableHead></TableRow></TableHeader><TableBody>{rows.length ? rows.map((row) => <TableRow key={row.id}><TableCell className="tabular-nums">{row.createdAt.toLocaleString("zh-CN", { timeZone: "America/Toronto" })}</TableCell><TableCell>{row.actorType}</TableCell><TableCell className="font-medium">{row.action}</TableCell><TableCell>{row.entityType} · {row.entityId}</TableCell><TableCell className="max-w-sm whitespace-normal">{row.reason}</TableCell></TableRow>) : <TableRow><TableCell className="h-28 text-center text-muted" colSpan={5}>暂无符合条件的审计记录。</TableCell></TableRow>}</TableBody></Table></section></div>;
}
